[package]
name = "runar_common"
version = "0.1.0"
edition = "2021"
authors = ["Runar Team"]
description = "Common traits and utilities for the Runar P2P stack"

[features]
default = []
abstract_service = []

[dependencies]
serde = { version = "1.0", features = ["derive"] } 